# Generated by Django 3.0.2 on 2020-08-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='Null', max_length=400),
        ),
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.TextField(default='Null'),
        ),
    ]
